### ISSUE TITLE
Workin together with bootstrap-table

### ISSUE THREAD

**Issue by promogest** [markcell/jQuery-Tabledit#1]
Hi, i like so much this plugin. I need to know if it can work together with bootstrap-table. 
https://github.com/wenzhixin/bootstrap-table
i tried but when i refresh the table after pagination or search the table loose your plugin. 
Any help?

**Comment by markcell** [comment]
I think it works well when called in an event such as "onLoadSuccess" from bootstrap-table. This is because the jQuery-Tabledit must be executed whenever the table is also reloaded.

Exemplo com o [DataTables](http://www.datatables.net/):

```js
$('table').DataTable({
    serverSide: true,
    processing: true,
    ajax: {
        url: 'read.php',
        type: 'POST'
    }
});

$('table').on('draw.dt', function() {
    $(this).Tabledit({
        url: 'update.php',
        columns: {
            identifier: [0, 'id'],
            editable: [[1, 'name'], [2, 'email']]
        }
    });
});
```

**Comment by promogest** [comment]
It works!
$('#table').on('load-success.bs.table', function() {
$('#table').Tabledit({
                url: '/pg/as_CategoriaArticolo/Update',
                columns: {
                    identifier: [0, 'index'],
                    editable: [, [1, 'denominazione'], [2, 'denominazione_breve']]
                }
            });
});

**Comment by njovujsh** [comment]
This solution is beautiful thanks a bunch

**Comment by lewimuchiri** [comment]
It will be best to provide a `hasTabledit()` function to show whether Tabledit has been initialized on a table before. In that way, you will not have to re-initialize it (which leads to addition of duplicate Edit buttons on the table rows). Also, it is not possible to delete a non-existent Tabledit hence the `hasTabledit()` function is really needed.

For now I am working with this:
```
function hasTabledit(table) {
    return $('tbody tr:first td:last > div', table).hasClass("tabledit-toolbar");
}
```
but it is not the best solution
