### ISSUE TITLE
jQuery UI Sortable serialize() method does not work with Tabledit

### ISSUE THREAD

**Issue by wololock** [markcell/jQuery-Tabledit#10]
I just tried to use Tabledit with jQuery UI Sortable and it seems like there is a conflict if you try to use both libraries. The problem is that Tabledit changes id of `tr` elements from e.g.

    id="item-100" -> id="100"

To use jQuery UI Sortable serialize() method (http://api.jqueryui.com/sortable/#method-serialize) on table rows we need to have their ids in a format like "item-[number]" or "item_[number]" which is not possible with current version of Tabledit.

What do you think about making both libraries compatible?

**Comment by markcell** [comment]
Yes, I will change this attribute to 'date-id' or something in the next update.

For now, you can change this line or comment it:
https://github.com/markcell/jQuery-Tabledit/blob/master/jquery.tabledit.js#L104

I do not use this attribute, I send inputs, including hidden input with id.

**Comment by wololock** [comment]
I also found alternative workaround. `sortable` method may be called like this:

    jQuery('table tbody').sortable('serialize', {key: 'id', expression: /(.+)/})

Then the query string looks similar to: `?id=1&id=2&id=3&...`. It works well in that case.

**Comment by markcell** [comment]
;)
