### ISSUE TITLE
Tabbing to next table cell in row

### ISSUE THREAD

**Issue by structure-pm** [markcell/jquery-tabledit#11]
I don't have this project set up in github right now. However I just added these few lines to keyup() section for quickly saving and moving to the next TD on 'tab' press:

                case 9: // Tab.
                    Edit.submit($td);
                    Mode.edit($td.closest('td').next());
                    break;

**Comment by markcell** [comment]
I'll add it in the next minor version, only if you are using the inline edit mode without button "Edit".

**Comment by markcell** [comment]
Done.
