### ISSUE TITLE
Submit all cells of a row on enter 

### ISSUE THREAD

**Issue by Atiquekhan** [markcell/jquery-tabledit#114]
I am using this plugin and I am having a issue. I want to use it like spreadsheet without edit button. 

When i change something and enter it only sends that specific to server and all other cells are empty. 
I want to send all cells on single change.. Thanks

**Comment by dicm** [comment]
As far as I know, you have to edit the javascript function quite a bit to get what you want.

Is there a reason you don't want it to send just the one cell. It saves data and less risk of hitten the limit of the server is smaller. 

I am using this just like a spreadsheet and i am using it on single cells. I have to change a bit to make it work for my setup ( hidden fields with cell name for the database and other stuff). But compared to my google sheet its the same i see, just only one cell saving (and no reason for me to save a full row when only one thing is changed).

**Comment by Atiquekhan** [comment]
Thanks for your answer dicm.. Actually I have in my case one cell update effects other cells calculations and we have to update those updated cells as well. I have done this using custom ajax request for specific cells, its working fine now..  Thanks

**Comment by Atiquekhan** [comment]
One thing I want to ask.. Can we submit cell when user leaves the cell ? Currently we have to press enter to submit cell. Thanks

**Comment by dicm** [comment]
Submit on leave can be done yes. 

If you look into the .js file and find the reset function (around line 260).

        reset: function(td) {
                $(td).each(function() {


Then add the submit code (This this is the code you will need to add: 
      Edit.submit($(this).parents('tr').find('td.tabledit-edit-mode'));
)

**Comment by Atiquekhan** [comment]
It worked, thanks .. I really appreciate your answers.. 
Thanks again..
