### ISSUE TITLE
Required help. I want to edit cell on double click not on single click..

### ISSUE THREAD

**Issue by Atiquekhan** [markcell/jquery-tabledit#117]
Single click edit is creating problem and I want when user want to edit he/she should click twice to edit cell.  Advance thanks

**Comment by dicm** [comment]
Hi @Atiquekhan  

You should be able to do        

 eventType: 'dblclick',
in the JS file. (it it set to click)

**Comment by Atiquekhan** [comment]
Thank you, it worked.. :+1:
