### ISSUE TITLE
Target table body (tbody)

### ISSUE THREAD

**Issue by structure-pm** [markcell/jquery-tabledit#12]
Presently as written the plugin will target `tfoot` cells as well as `tbody` cells. Recommend changing code and usage to require and target `tbody` specifically -- as `tfoot` is more often going to be used to update totals from body rows, etc (not user-modified).

Very simple with this call:
`var $td = $table.find('tbody td:nth-child(' + (parseInt(settings.columns.identifier[0]) + 1) + ')');`

**Comment by markcell** [comment]
I'll add it in the next minor version.

Thanks.

**Comment by markcell** [comment]
Done.
