### ISSUE TITLE
Set on editMode a row

### ISSUE THREAD

**Issue by promogest** [markcell/jQuery-Tabledit#3]
I added a button in the "action" column header and onclick i add a row with empty fields. It works but how can i trigger the edit button of that ( the first ) row? 
thanks

**Comment by markcell** [comment]
In the current version there is still no way to do this. I was thinking to add the function to add rows in the next version.

For now you can try to replicate what I do to prepare the row for editing using the same classes or add new row with a modal window or something like that.

**Comment by promogest** [comment]
i changed that:
                        if ($table.find('th.tabledit-toolbox-column').length === 0) {
                            $table.find('tr:first').append('<th class="tabledit-toolbox-column"><button type="button" id="add_row" class="btn btn-success">ADD ROW</button></th>');
              }

and use :
$('#add_row').click(function (e) {
    $('#mytable').bootstrapTable('insertRow', {
index: 0,
row: {
id: "",
denominazione: "",
denominazione_breve: ""
}
});
$('#mytable').Tabledit({
                url: '/pg/as_CategoriaArticolo/Update',
                hideIdentifier: true,
                columns: {
                    identifier: [0, 'id'],
                    editable: [[1, 'denominazione'], [2, 'denominazione_breve']]
                },
            });
var indexx = $("#mytable > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(4) > div:nth-child(1) > button:nth-child(1)").click();
in my file js ... 
No i have a ADD ROW button in the bottom of your action column, it add an empty row and click the edit button.
How can i catch the 
onSuccess(data, textStatus, jqXHR):
have you some example?
thanks for your patience

**Comment by markcell** [comment]
```js
$('#table').Tabledit({
    url: 'example.php',
    hideIdentifier: true,
    columns: {
        identifier: [0, 'id'],
        editable: [[1, 'name'], [2, 'email']]
    },
    onSuccess: function(data, textStatus, jqXHR) {
        // Occurs whenever it is made a successful ajax request (edit or remove action).
        console.log(data);
        console.log(textStatus);
        console.log(jqXHR);
    }
});
```

**Comment by promogest** [comment]
Thanks, it works. I have a beautiful inline edit/insert/delete table system. 
I need  to add a button to cancel the operation when delete is pressed and we are in the "confirm" step.

**Comment by markcell** [comment]
For now, when you press 'esc' key the 'Confirm' button change to 'Remove' again. It is also thought to add the restore function after removal in a future update.

**Comment by anitha1arunkumar** [comment]
Hi ,
I wanted to allow tabledit with dynamic columns . Is it possible to use tablesorter column-selector with tabledit... I want to make a table with column toggle and inline edit ... So with column toggle the column positions will change.. Please Suggest whether in tabledit it is possible to handle  dynamic columns
