### ISSUE TITLE
How can I add row for tables ?

### ISSUE THREAD

**Issue by smarttang** [markcell/jquery-tabledit#31]
RT,how can i add row for tables? 
example:
http://thevectorlab.net/flatlab/editable_table.html

In demo ,I can't find add code ??
I need change、delete 、add in tables.
Can't you have add demo in plugin??

**Comment by salfredogonzalez** [comment]
So I guess, I don't have any look, if your post is from 4 years ago, and I am looking for the same thing.

**Comment by smarttang** [comment]
emmmm. ok, fine!
