### ISSUE TITLE
Can't make it work with only 1 editable column

### ISSUE THREAD

**Issue by supercharlez** [markcell/jquery-tabledit#33]
So in my JS I'm using this
`editable: [1, 'Search']
`
But it's not working. The buttons don't trigger any action. 

If I do 
`editable: [[1, 'Search'], [2, 'Name']]`

It works... 

How can I make it work for only 1 editable column ? Thanks

**Comment by markcell** [comment]
`editable: [[1, 'Search']]` instead of `editable: [1, 'Search']`
