### ISSUE TITLE
Edit row successfully stored in php codeigniter but tabledit returns red

### ISSUE THREAD

**Issue by redman5087** [markcell/jQuery-Tabledit#4]
I'm using the script and it is working and storing also succeesfully in php codeigniter but Tabledit returns that it failed but that is not the case.

Can you help me

**Comment by markcell** [comment]
The table row turns red only if the ajax request fails: https://github.com/markcell/jQuery-Tabledit/blob/master/jquery.tabledit.js#L318.

Checks if the server response is returning an error status code. Use the hooks "onSuccess()" and "onFail()" to check what the server returned:

```js
$('#table').Tabledit({
  url: 'example.php',
  columns: {
      identifier: [0, 'id'],
      editable: [[1, 'name'], [2, 'email']]
  },
  onSuccess: function(data, textStatus, jqXHR) {
      console.log(data);
      console.log(textStatus);
      console.log(jqXHR);
  },
  onFail: function(jqXHR, textStatus, errorThrown) {
      console.log(jqXHR);
      console.log(textStatus);
      console.log(errorThrown);
  }
});
```

**Comment by redman5087** [comment]
I did what you told and the error message is:

SyntaxError: Unexpected token < {stack: (...), message: "Unexpected token <"}


But the data is stored in the database.

Could you help,

Thanks.

**Comment by markcell** [comment]
It seems to me you have an error on the server side script. Probably after the code that writes the data in the database.

**Comment by redman5087** [comment]
In chrome with network inspector it gives me a status 200, so the php script is executed ok and there's no preview response, that should be ok?

Thanks again.!

**Comment by markcell** [comment]
It's strange to be happening this. What kind of data you send in server response?

**Comment by markcell** [comment]
Try to return JSON response.

**Comment by markcell** [comment]
Have you solved this issue?

I tried the plugin with the following example: https://github.com/markcell/jQuery-Tabledit/blob/master/example.php.

And if an error occurs in the execution, returns a response with status code 200. Probably the errors/exceptions are not being handled as some frameworks do.

Almost certainly there is some error in the PHP script that is related to this: <code>SyntaxError: Unexpected token < {stack: (...), message: "Unexpected token <"}</code>.

**Comment by redman5087** [comment]
"Unexpected token <" probably means that you are returning html from your php script.

I solved indeed this problem by inserting the data in the database with php and making sure I'm not returning any html.

However, it still gives a red line and I assume it is related with Json.

In firefox I get:
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Stack trace:
n.parseJSON@http://localhost/redman/boekhouden/assets/js/jquery.js:4:5304
vc@http://localhost/redman/boekhouden/assets/js/jquery.js:4:7397
x@http://localhost/redman/boekhouden/assets/js/jquery.js:4:10802
.send/b/<@http://localhost/redman/boekhouden/assets/js/jquery.js:4:14767

in Chromium I get:
 SyntaxError: Unexpected end of input {stack: (...), message: "Unexpected end of input"}

**Comment by markcell** [comment]
Check if your JSON response is correct. I'm not understand what can be more.

Sorry I can not help more :(

**Comment by redman5087** [comment]
I didn't see the example.php :+1: 
returning the data with json gives me no longer a red line, but an orange line

console log gives no error and a success status..

should it be a green line?

**Comment by matthers** [comment]
I also receive a yellow row when the data is saved. I presume this is the
correct way to work

**Comment by markcell** [comment]
Yes. The yellow row is to indicate that this row has been edited.
But there are the following options for changing it:

dangerClass: class for row when ajax request fails (default = 'danger')
warningClass: class for row when save changes (default = 'warning')
mutedClass: class for row when is deleted (default = 'text-muted')
