### ISSUE TITLE
How to hide action column when table is empty?

### ISSUE THREAD

**Issue by nicolaeturcan** [markcell/jquery-tabledit#46]
Hi @markcell, thanks you for this awesome package.

I have the next issue. When there is no data in datatable, the action column is still there.
![seleccio_147](https://cloud.githubusercontent.com/assets/7248811/20793700/a1fe5312-b7c8-11e6-9b9a-ad494a4667f4.png)

I tried hidding it like this: 
```php
         if(table.rows({filter: 'applied'}).data().length == 0) {

                    $('.tabledit-toolbar-column').hide();
                    $(".table td:nth-child(2)").hide();
         }
```
but it didn't work because after hidding, it is reinitialized and showed again. I also tried to redefine it like this:

```php
         if(table.rows({filter: 'applied'}).data().length == 0) {

                 $('.dataTable').Tabledit({
                        deleteButton: false,
                        editButton: false,
                        columns: {
                            identifier: [0, 'id'],
                            editable: []
                        },
                    });
         }
```
But it had no effect.

**Comment by ylvinzk** [comment]
This was my solution for the delete button:

if ($("#Table tbody tr td").hasClass("dataTables_empty")) {
        $(".tabledit-delete-button").hide();
    }

Use it after the initialization of Tabledit

**Comment by rs2pt** [comment]
currently (2021) this worked for me, since it didn't render the class "dataTables_empty" so:

if (!$("#obj_table tbody tr td").hasClass("tabledit-view-mode")) {
	$(".tabledit-toolbar").hide();
}
