### ISSUE TITLE
Delete button doesn't hide 

### ISSUE THREAD

**Issue by Rohaan-Ishfaq** [markcell/jQuery-Tabledit#5]
I set deleteButton to false but delete button doesn't hide from the table. Why?

**Comment by markcell** [comment]
I tested it with 'deleteButton: false' and works well. See example 5, does not have the delete button.

**Comment by Rohaan-Ishfaq** [comment]
Yeah Im also using deleteButton:false but it never worked.

**Comment by markcell** [comment]
It's weird. Are you using the latest version 1.2.0? In this version is 'deleteButton', the previous was 'removeButton'.

**Comment by Rohaan-Ishfaq** [comment]
Oh cool sorry me bad. I used removeButton and it worked.

**Comment by markcell** [comment]
For version 1.1.* See this link: https://github.com/markcell/jQuery-Tabledit/tree/v1.1.1

Forget the badge that says 1.2.0. It is updated with the latest version number automatically.

**Comment by Rohaan-Ishfaq** [comment]
Rohaan invites you to join Bayt.com


	
		
			
				
					
					
						
							
								
									
										
											
												
												
													
														
													
												
											
										
										 
											
												
													
														
															
																
																
																	
																		Rohaan Ishfaq invites you to join Bayt.com
																	
																
																
															
															
																
																
																	  
																	
																	  
																
																
															
															
																
																
																	
																		  
																		Rohaan Ishfaq
																		  
																		Software Engineer
																	
																
																
															
															
															
																
															
														
													
												
											
										
										
										 
											
												
													
													Rohaan has invited you to use Bayt.com, the Middle East's #1 job site and register for free.
													
												
											
										
										
											
												
												
												
												
															
																
																
																	
																		Accept Invitation
