### ISSUE TITLE
Drop-down selected value get erased after click on edit pencil.

### ISSUE THREAD

**Issue by MangeshK3007** [markcell/jquery-tabledit#53]
I have table with some data and that table contain one cell as drop-down list, while editing particular row, the selected value from drop-down list get erased.

Can anyone tell me how to retain/fix the selected value while click on edit.

**Comment by julimat** [comment]
Hi. Did you resolve the problem? I'm in the same issue...thank you !

**Comment by MangeshK3007** [comment]
Hi, yes I resolve the problem,
Actually value not get erased, the white space append to the string
automatically, so use trim to get the value,
if you debug your code you get the value with the space.

Thanks.
