### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by matthers** [markcell/jQuery-Tabledit#6]
Hello,

I wanted to ask if you can add a function to edit a date by adding a small calendar from which the date can be chosen.
I have tried a few ways to implement it but it did not work.

Also, I wanted to ask if it's possible for errors to mention what generated them(ex: error when saving Lastname , error when saving id)

**Comment by markcell** [comment]
Example with [eternicode/bootstrap-datepicker](https://github.com/eternicode/bootstrap-datepicker) and [markcell/jQuery-Alertiny](https://github.com/markcell/jQuery-Alertiny):

```js
$('table').Tabledit({
  url: 'example.php',
  columns: {
    identifier: [0, 'id'],
    editable: [[1, 'date'], [2, 'name']]
  },
  onSuccess: function(data) {
    // Example of response from PHP script:
    // json_encode(array('type' => 'error', 'message' => 'Example.')); 
    if (data.type && data.message) {
      $('.alert-container').Alertiny(data.type, data.message);
    }
  },
  onDraw: function() {
    // Select all inputs of second column and apply datepicker each of them
    $('table tr td:nth-child(2) input').each(function() {
      $(this).datepicker({
        format: 'yyyy-mm-dd',
        todayHighlight: true
      });
    });
  }
});
```

**Comment by matthers** [comment]
Thanks, this works great.

**Comment by matthers** [comment]
Can you please help me with an example for the validation of another fields?
I need a min-max number validation and something for just alphanumerical chars.

I tried to use https://github.com/jzaefferer/jquery-validation but i think i didn't use it right as i get no validation, no errors.

**Comment by gabmen1711** [comment]
Hello I was trying to do the same thing, I need to modify dates using Jquery Tabledit and with your example i was able to add the datepicker in the table when click to edit, but when i send the info to the PHP to be storaged in the database even when it says success it does not safe the info, how did you manage to Storage the date in the Data Base?

Hope you can help me and i really appreciate it.

regards!

**Comment by matthers** [comment]
@gabmen1711 make sure your DB table is set up properly(ex: Datetime) and that you send it in the proper format.

You might need to change the format(ex: DD-MM-YYYY) or remove the seconds and so on.

Test using echo $date-from-datepicler to see how it's sent and then compare to what your DB expects.

**Comment by gabmen1711** [comment]
Thank you very much for your help!
One more thing when I click the Edit Button it popups automaticly the Calendar, as I have 3 different dates inputs it popups the 3 at the same time, do you know if its possible to prevent them to auto popups when i click edit or if its possible to not highlight the inputs when i click edit i believe that is why they popup automaticly!

Thanks again for the help

**Comment by tuonglv** [comment]
@gabmen1711: comment line 237 
`$input.focus();`

**Comment by sandeepsangole** [comment]
Could someone share jsfiddle for date picker. I have included bootstrap-datepicker3.css ,bootstrap-datepicker3.css.map and altertiny js in my application. But I am getting javascript error as undefined function near..$(this).datepicker({

I am new to front end development so kind of struggling with this. Any help is appreciated.

**Comment by sandeepsangole** [comment]
Its working !!

**Comment by grim1365** [comment]
Still cant remove the DatePicker AutoPopup. Waiting for answers thanks

**Comment by xbox2007** [comment]
hello , 
i try to use datepicker in my Code but not working with me , 

please if any one  can share working code 

thanks a lot

**Comment by xbox2007** [comment]
> Thanks, this works great.

please can you share full code of page , i try use same your code but its not working with me 

thanks a lot

**Comment by Hancockm910** [comment]
When I put in the onDraw code everything on my page becomes un-editable. Any idea what I'm missing?

**Comment by MarioLara76** [comment]
Hi, from this example
https://trac.edgewall.org/ticket/12228
This for the autocomplete:
 $(this).prop("autocomplete", "off");
This is the code
$('#tblrevop tr td:nth-child(5) input').each(function() {
  $(this).datepicker({
	format: 'mm/dd/yyyy',
	todayBtn: true,
	todayHighlight: true
  });
  $(this).prop("autocomplete", "off");
});
