### ISSUE TITLE
Error: Tabledit only works when applied to a table.

### ISSUE THREAD

**Issue by l3luesmile** [markcell/jquery-tabledit#62]
why error , can help me thank you
HTML

> <table id="example1" class="table table-striped table-hover">
>                   <thead>
>                     <tr>
>                       <th>#</th>
>                       <th>NAME</th>
>                       <th>URL</th>
>                     </tr>
>                   </thead>
>                   <tbody>
>                     <tr>
>                      <td>id</td>
>                      <td>NAME</td>
>                      <td>URL</td>
>                    </tr>
>                  </tbody>
>                </table>
> <table id="example2" class="table table-striped table-hover">
>                   <thead>
>                     <tr>
>                        <th>#</th>
>                   <th>NAME</th>
>                   <th>DETAIL</th>
>                   <th>EMAIL</th>
>                   <th>DATE</th>
>                     </tr>
>                   </thead>
>                   <tbody>
>                     <tr>
>                     <td>id</td>
>                  <td>NAME</td>
>                  <td>DETAIL</td>
>                  <td>EMAIL</td>
>                  <td>DATE</td>
>                    </tr>
>                  </tbody>
>                </table>

SCRIPT
`	$(document).ready(function() {
		$('#example1').Tabledit({
			url: 'example.php',
			deleteButton: false,
			columns: {
				identifier: [0, 'id'],
				editable: [[1, 'name'], [2, 'url']]
			},
		});	
		$('#example2').Tabledit({
			url: 'example.php',
			editButton: false,
			columns: {
				identifier: [0, 'id'],
				editable: [[1, 'subject'], [2, 'detail'], [3, 'email'], [4, 'datetime']]
			}
		});
	});`

**Comment by manishhiran** [comment]
Hi there,

Has this issue be resolved? I'm still getting the error: Error: Tabledit only works when applied to a table.
