### ISSUE TITLE
add attributes to post request

### ISSUE THREAD

**Issue by alexanderkraemer** [markcell/jquery-tabledit#70]
Would be a pretty awesome thing to have the possibility to add any kind of arguments to the POST Request.
Laravel e.g. requires the csrf token otherwise the request will not be accepted.
Is there a possibility to do this already which I may have missed?

**Comment by rahi-rajeev** [comment]
Hi,
Please see this way you can add csrf token
<script type="text/javascript">
   window.Laravel = {"csrfToken":"{{ csrf_token() }}"};
</script>
$(document).ajaxSend(function(e, xhr, options) {
          var sid = window.Laravel.csrfToken;
          xhr.setRequestHeader("X-CSRF-Token", sid);
 });
