### ISSUE TITLE
Little problem of design !

### ISSUE THREAD

**Issue by Twimmcook** [markcell/jquery-tabledit#72]
![capture du 2017-08-31 13-41-08](https://user-images.githubusercontent.com/8591577/29921715-eff63178-8e52-11e7-87a5-90955f049a31.png)
Hello ,
How can this small line problem be corrected? And how does one give a name to the column, such as "Actions" for example?
Thanks

**Comment by BluesatKV** [comment]
Test new version [https://github.com/BluesatKV/jquery-tabledit](https://github.com/BluesatKV/jquery-tabledit).

**Comment by Twimmcook** [comment]
Thanks for your reply !
I think the best it's use jquery-tabledit.js, not jquery-tabledit.min.js ?

**Comment by BluesatKV** [comment]
It does not matter how you use it from **markcell**

From me:
jquery-tabledit.min.js is version 1.2.6
jquery-tabledit.js is version 1.2.7 development (is better than 1.2.6 and is for tester)

**Comment by Twimmcook** [comment]
ok i'll try jquery-tabledit.min.js
